### PR TITLE
Feat : Landing Page

### PR DESCRIPTION
**Pull request by anuj-kumary**
Completed Landing Page:-
- Added Navbar components
- Sidebar components
- Note components

ScreenShot:-
Screenshot from 2022-03-23 23-22-37
Screenshot from 2022-03-23 23-22-55

### CODE REVIEW

**Review by vinc3nati — APPROVED** [review]
Well maintained code

**Review by PeeyushPrashant — APPROVED** [review]
code looks clean

**Review by romabulani — APPROVED** [review]
- UI is looking nice
- Clean code and quite understandable classnames
- Good to merge

**Review by Shah-Arsalan — APPROVED** [review]
Couldn't find anything wrong with this code.
Folder structure is good.
Proper css is there 
I would suggest you merge !

**Pull request merged**
